apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: project-9b88f3d7-01da-4e70-9fe
      auth:
        workloadIdentity:
          clusterLocation: europe-north2-a
          clusterName: my-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
